### ISSUE TITLE
Generator failes when quering dependencies

### ISSUE THREAD

**Issue by subwaystation** [inrupt/generator-solid-react#286] opened 2019-12-09 12:00 UTC
**Describe the bug**
I tried to generate the react app template via `yo` and also tried #193, but it failed:

```bash
Installing dependencies...
npm WARN deprecated jest-dom@3.5.0: 🚨 jest-dom has moved to @testing-library/jest-dom. Please uninstall jest-dom and install @testing-library/jest-dom instead, or use an older version of jest-dom. Learn more about this change here: https://github.com/testing-library/dom-testing-library/issues/260 Thanks! :)
npm WARN deprecated react-testing-library@6.1.2: 🚨  react-testing-library has moved to @testing-library/react. Please uninstall react-testing-library and install @testing-library/react instead, or use an older version of react-testing-library. Learn more about this change here: https://github.com/testing-library/dom-testing-library/issues/260 Thanks! :)
npm WARN deprecated dom-testing-library@3.19.4: 🚨  dom-testing-library has moved to @testing-library/dom. Please uninstall dom-testing-library and install @testing-library/dom instead, or use an older version of dom-testing-library. Learn more about this change here: https://github.com/testing-library/dom-testing-library/issues/260 Thanks! :)
npm WARN deprecated core-js@2.6.4: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/gwicke/web-streams-polyfill.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 140.82.118.4]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heumos/.npm/_logs/2019-12-09T11_51_02_849Z-debug.log
```

**To Reproduce**
`yo @inrupt/solid-react`

**Expected behavior**
Generate the template.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser Firefox
 - Version 71.0
 - Node: v12.11.1
 - npm: 6.12.0

Thanks!

**Comment by james-martin-jd** [comment] 2019-12-09 21:17
Thanks for the bug report - I've seen this issue before when access to github.com was not available from the computer running the yeoman command. Can you confirm if you can access github.com? If so, can you try again? It's possible github had a hiccup or something as well.

If it's still failing, try installing [https://git-scm.com/downloads](Git) on your computer if it isn't already installed.

**Comment by subwaystation** [comment] 2019-12-10 14:27
I am still seeing this error, I tried several times during the last 16 hours.
I already had `git` installed:
```[heumos@wave swat4hcls]$ git --version
git version 2.24.0
```
I think the problem is that `git` tries to reach `web-streams-polyfill` via `ssh` instead of `https`.

**Comment by subwaystation** [comment] 2019-12-10 14:28
Indeed `https` works:

```
[heumos@wave swat4hcls]$ /usr/bin/git ls-remote -h -t https://github.com/gwicke/web-streams-polyfill.git
77d2ed141fbc2d9170ebf9e2bcefb8b39a513be9	refs/heads/master
42c488428adea1dc0c0245014e4896ad456b1ded	refs/heads/spec_performance_improvements
49c3c5363045edd18e186d7cd880917120395d47	refs/tags/v1.1.0
29c7d91e9f062426eb423bb34af5d4193f4183c1	refs/tags/v1.1.0^{}
```

**Comment by james-martin-jd** [comment] 2019-12-10 15:52
For a temporary fix, try cracking open the package-lock.json file and updating the `web-streams-polyfill` links from git:// to https://

I'll look for a more long-term fix, the issue is this isn't a dependency of ours directly, but rather dependency-of-a-dependency.

**Comment by subwaystation** [comment] 2019-12-11 12:41
Unfortunately, there is not `package-lock.json` created because `npm` exists with an error code.
Any other suggestions?

**Comment by michielbdejong** [comment] 2019-12-12 07:30
@james-martin-jd isn't this essentially a duplicate of #281?

**Comment by james-martin-jd** [comment] 2019-12-12 15:30
@michielbdejong that was my thought too, `npm ls` on the package seems to imply it's still coming from Comunica, even in v2.8.0, and our code added the same webpack code as ldflex did: 
```
      // Disable shims for supported browser features
      'web-streams-polyfill': 'window',
```

**Comment by james-martin-jd** [comment] 2019-12-17 20:41
@subwaystation if you're interested, you could test the new RC version to see if that fixes your problem. You can install it with `npm install -g @inrupt/generator-solid-react@rc`, which has made some changes to dependencies. I don't see the web-streams-polyfill locally in npm ls anymore on that RC.

**Comment by james-martin-jd** [comment] 2019-12-18 20:47
Today we released a new version of the generator which no longer has a dependency on the package giving you problems. I tested locally and no longer see that package installed.

**Closed by james-martin-jd** 2019-12-18 20:47 UTC

**Comment by subwaystation** [comment] 2020-01-10 13:23
Now it works, thank!
